# Generated by Django 3.1.1 on 2020-10-25 11:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201025_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
