# Generated by Django 3.1.1 on 2020-10-30 05:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_pinplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='love',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
