# Generated by Django 4.2 on 2023-09-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='image',
            field=models.ImageField(blank=True, default='traveler/default.jpg', null=True, upload_to='traveler/'),
        ),
    ]
